### ISSUE TITLE
docker-compose doesn't work at all

### ISSUE THREAD

**Issue by al-sabr** [hypriot/image-builder-odroid-c2#26]
```

$ docker-compose -up -d
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 10, in <module>
    from docker.errors import APIError
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 8, in <module>
    import six
ImportError: No module named six
```

**Comment by docbobo** [comment]
Is this on all your devices?

**Comment by al-sabr** [comment]
No I tried on the other device and I get this error : 

```
$ docker-compose up
WARNING: The ARANGO_RANDOM_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ARANGO_NO_AUTH variable is not set. Defaulting to a blank string.
WARNING: The ARANGO_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
ERROR: In file './docker-compose.yml', network 'driver' must be a mapping not a string.

```

**Comment by docbobo** [comment]
At least the ARANGO warnings seem to suggest that docker-compose is working in general... Did you manage to solve your problem?

**Comment by al-sabr** [comment]
Somehow just restarting the device made dc work again it is strange...
